# Generated by Django 5.2.17 on 2026-09-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['learning_order', 'title']},
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='learning_no_status_afeaad_idx',
            old_name='learning_no_status_2c919c_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='learning_no_title_36c0ac_idx',
            old_name='learning_no_title_7e30a2_idx',
        ),
    ]
