from django.core.management.base import BaseCommand
from django.utils.text import slugify
from learning.models import Category, Note, Tag

NOTES = [
    (1, "Instalar Django y entender el proyecto", "Aprende qué instala Django, para qué sirve un entorno virtual y cómo se organiza un proyecto nuevo.", """## Objetivos\n\nAl terminar podrás crear un entorno aislado, instalar dependencias y explicar la diferencia entre proyecto, aplicación y servidor de desarrollo.\n\n## ¿Qué es Django?\n\nDjango es un framework web de Python. No es una aplicación única: es un conjunto de herramientas para resolver problemas repetidos como URLs, bases de datos, autenticación, formularios, administración y seguridad.\n\n## Entorno virtual\n\nCada proyecto debe tener sus propias dependencias para evitar que una actualización de otro proyecto lo rompa.\n\n```bash\npython -m venv .venv\nsource .venv/bin/activate\npython -m pip install --upgrade pip\npip install Django\n```\n\nEn Windows la activación es `.venv\\Scripts\\activate`. El archivo `requirements.txt` convierte las dependencias en una receta reproducible.\n\n## Crear y leer un proyecto\n\n```bash\ndjango-admin startproject config .\npython manage.py runserver\n```\n\n`manage.py` es la entrada para comandos administrativos. `settings.py` contiene configuración, `urls.py` es el mapa principal y `wsgi.py`/`asgi.py` son puntos de entrada para servidores.\n\nUna **aplicación** agrupa una capacidad del dominio, como `learning` o `webapi`; un **proyecto** conecta todas las aplicaciones y decide cómo se ejecuta el conjunto.\n\n## Errores comunes\n\n- Instalar paquetes sin activar `.venv`.\n- Crear el proyecto en una carpeta distinta y perder el contexto de `manage.py`.\n- Subir `.env` o contraseñas al repositorio.\n\n## Práctica\n\n1. Ejecuta `python manage.py check`.\n2. Cambia el puerto con `python manage.py runserver 8001`.\n3. Localiza en `config/settings.py` dónde se registran las aplicaciones.\n4. Escribe con tus palabras qué diferencia hay entre una app y un proyecto.\n\n> Comprobación: si puedes seguir una petición desde el servidor hasta `config/urls.py`, ya tienes el mapa inicial.""", "fundamentals", "beginner", ["instalacion", "proyecto"]),
    (2, "Modelos: convertir conceptos en datos", "Aprende a diseñar modelos, ejecutar migraciones y consultar PostgreSQL usando el ORM de Django.", """## Objetivos\n\nAprenderás a representar información con clases Python, entender qué hacen las migraciones y consultar objetos sin escribir SQL para cada operación.\n\n## Del concepto a la tabla\n\nUn modelo describe una entidad persistente. Cada atributo se convierte en una columna y las relaciones se convierten en claves foráneas o tablas intermedias.\n\n```python\nfrom django.db import models\n\nclass Book(models.Model):\n    title = models.CharField(max_length=200)\n    published_at = models.DateField(null=True, blank=True)\n    is_read = models.BooleanField(default=False)\n```\n\n`CharField` necesita un límite; `DateField` conoce fechas; `BooleanField` expresa sí/no. `null=True` describe la base de datos y `blank=True` permite que los formularios acepten el valor vacío: son decisiones relacionadas, pero no idénticas.\n\n## Migraciones\n\nUna migración es un registro versionado de cambios de esquema.\n\n```bash\npython manage.py makemigrations\npython manage.py migrate\n```\n\n`makemigrations` compara modelos y genera instrucciones. `migrate` las aplica a la base configurada. Nunca confundas cambiar el archivo Python con cambiar realmente la base de datos.\n\n## ORM básico\n\n```python\nBook.objects.create(title="Django claro")\nBook.objects.filter(is_read=False)\nBook.objects.get(pk=1)\nBook.objects.order_by("-published_at")\n```\n\n`filter()` devuelve un queryset que puede seguir componiéndose. `get()` espera exactamente un resultado y lanza una excepción si no existe o hay más de uno.\n\n## Relaciones y reglas\n\nEn este proyecto `Note` pertenece a una `Category` y puede tener muchos `Tag`. `PROTECT` evita eliminar una categoría que todavía tiene apuntes. La base de datos ayuda a garantizar unicidad en slugs y nombres.\n\n## Práctica\n\n1. Añade un campo `estimated_minutes` a `Note`.\n2. Genera la migración y revisa el archivo creado.\n3. Consulta los apuntes publicados desde el shell con `python manage.py shell`.\n4. Explica cuándo usarías `get()` y cuándo `filter()`.\n\n> Comprobación: si puedes describir qué cambió en PostgreSQL después de `migrate`, entendiste el ciclo modelo → migración → tabla.""", "fundamentals", "beginner", ["modelos", "orm"]),
    (3, "URLs y views: conectar una petición", "Sigue el viaje completo de una petición HTTP desde una URL hasta una vista y su respuesta.", """## Objetivos\n\nAprenderás a leer un mapa de URLs, capturar parámetros y elegir entre vistas basadas en funciones o clases.\n\n## La URL como contrato\n\n```python\nfrom django.urls import path\nfrom .views import NoteDetailView\n\nurlpatterns = [\n    path("notes/<slug:slug>/", NoteDetailView.as_view(), name="note-detail"),\n]\n```\n\n`<slug:slug>` captura una parte de la URL y la entrega a la vista como argumento `slug`. El `name` evita repetir rutas en templates y redirecciones: `{% url 'note-detail' slug=note.slug %}`.\n\n## Qué hace una vista\n\nUna vista recibe `request`, obtiene o transforma datos y devuelve una respuesta. `DetailView` resuelve tareas repetidas: buscar un objeto, manejar un 404 y renderizar un template.\n\n```python\nclass NoteDetailView(DetailView):\n    model = Note\n    template_name = "web/note_detail.html"\n    slug_field = "slug"\n```\n\nEl queryset de esta vista filtra solo apuntes publicados. Esa regla pertenece al acceso a los datos, no al template.\n\n## El ciclo de una petición\n\n1. El navegador solicita `GET /notes/modelos/`.\n2. Django recorre `config/urls.py` y luego `web/urls.py`.\n3. La URL convierte `modelos` en `slug`.\n4. La vista busca el apunte.\n5. Django construye el contexto.\n6. El template genera HTML y devuelve una respuesta.\n\n## Errores útiles para aprender\n\n- `404`: la URL existe, pero el objeto no cumple el queryset.\n- `NoReverseMatch`: intentaste construir una URL con un nombre o parámetro incorrecto.\n- `TemplateDoesNotExist`: Django no encuentra el archivo indicado.\n\n## Práctica\n\n1. Añade una URL `/about/`.\n2. Crea una vista que devuelva un `HttpResponse` sencillo.\n3. Cambia temporalmente el filtro de publicados y observa qué aparece.\n4. Usa `{% url %}` en lugar de escribir rutas manualmente.\n\n> Comprobación: dibuja el flujo navegador → URLconf → view → contexto → template.""", "web", "beginner", ["urls", "views"]),
    (4, "Templates: mostrar datos con intención", "Aprende herencia, contexto, filtros y condiciones para construir HTML mantenible.", """## Objetivos\n\nAl terminar entenderás qué puede hacer un template y qué debe permanecer en Python.\n\n## Template y contexto\n\nUna vista entrega un diccionario de contexto; el template lo presenta.\n\n```python\nreturn render(request, "web/note_list.html", {"notes": notes})\n```\n\n```django\n{% for note in notes %}\n  <h2>{{ note.title }}</h2>\n{% empty %}\n  <p>No hay apuntes todavía.</p>\n{% endfor %}\n```\n\nLa etiqueta correcta es `{% empty %}`. Si escribes `{empty}`, Django lo tratará como texto común y aparecerá en pantalla.\n\n## Herencia\n\n`base.html` contiene la estructura compartida: navegación, CSS y footer. Las páginas hijas reemplazan bloques.\n\n```django\n{% extends "base.html" %}\n{% block title %}Mis apuntes{% endblock %}\n{% block content %}Contenido de la página{% endblock %}\n```\n\nEsto evita copiar la misma navegación en seis archivos.\n\n## Responsabilidades\n\nEl template puede recorrer, mostrar y enlazar datos. No debería decidir reglas de negocio, consultar la base de datos ni contener HTML generado desde entrada insegura. Django escapa variables por defecto; usa `|safe` únicamente cuando el contenido fue sanitizado explícitamente, como el Markdown de esta wiki.\n\n## Accesibilidad y claridad\n\nUsa títulos en orden, textos de enlace descriptivos, `label` para formularios y estados vacíos que indiquen cómo continuar. Un template es parte de la experiencia de aprendizaje, no solo decoración.\n\n## Práctica\n\n1. Añade un bloque `meta` al template base.\n2. Muestra el número de etiquetas de cada apunte.\n3. Crea un estado vacío distinto para una búsqueda sin resultados.\n4. Inspecciona el HTML final en el navegador.\n\n> Comprobación: identifica qué datos llegan desde la vista y qué decisiones pertenecen al template.""", "web", "beginner", ["templates", "html"]),
    (5, "Formularios y autenticación", "Valida datos enviados por el usuario y protege las acciones que crean o modifican apuntes.", """## Objetivos\n\nAprenderás la diferencia entre autenticación y autorización, cómo funciona un `ModelForm` y por qué el token CSRF es necesario.\n\n## Autenticación vs. autorización\n\n**Autenticación** responde: ¿quién eres? Django la resuelve con sesión, usuario y contraseña. **Autorización** responde: ¿puedes hacer esto? `LoginRequiredMixin` impide que una persona anónima cree o edite.\n\n```python\nclass NoteCreateView(LoginRequiredMixin, CreateView):\n    model = Note\n    form_class = NoteForm\n```\n\n## ModelForm\n\n`NoteForm` deriva sus campos del modelo. Así Django puede generar widgets y validaciones coherentes. El navegador valida algunas cosas, pero la validación real ocurre en el servidor: nunca confíes solo en JavaScript.\n\n```python\nclass NoteForm(forms.ModelForm):\n    class Meta:\n        model = Note\n        fields = ["title", "summary", "content", "category"]\n```\n\n## POST y CSRF\n\nLos formularios que cambian datos usan `POST` y deben incluir `{% csrf_token %}`. El token evita que otra página envíe una acción usando la sesión de una persona autenticada.\n\n## Flujo de guardado\n\n1. Se muestra el formulario con `GET`.\n2. La persona envía datos con `POST`.\n3. Django valida tipos, límites y campos obligatorios.\n4. Si hay errores, vuelve al formulario conservando mensajes.\n5. Si todo es correcto, guarda y redirige.\n\n## Errores comunes\n\n- Proteger la pantalla pero olvidar proteger la API.\n- Confiar en un campo oculto para decidir el propietario.\n- Usar `|safe` sobre texto enviado por el usuario sin sanitizarlo.\n\n## Práctica\n\n1. Intenta abrir `/notes/new/` sin sesión.\n2. Inicia sesión y envía un título vacío.\n3. Añade una validación para que el resumen tenga una longitud mínima.\n4. Comprueba que un apunte borrador no aparece en la portada.\n\n> Comprobación: explica qué protege CSRF y qué protege `LoginRequiredMixin`; no son la misma defensa.""", "web", "intermediate", ["formularios", "auth"]),
    (6, "Diseñar una API REST", "Construye una API JSON separada de los templates con serializers, viewsets, filtros, permisos y OpenAPI.", """## Objetivos\n\nAprenderás por qué una API es un contrato, cómo convertir modelos a JSON y cómo controlar quién puede leer o escribir.\n\n## Recursos y verbos HTTP\n\nEsta API trata los apuntes como recursos: `GET /api/notes/` lista, `GET /api/notes/<slug>/` muestra, `POST` crea, `PATCH` modifica y `DELETE` elimina. El estado HTTP también comunica el resultado: `200` éxito, `201` creación, `400` datos inválidos, `401/403` acceso insuficiente y `404` recurso inexistente.\n\n## Serializers\n\nUn serializer traduce entre objetos Django y representaciones JSON. También valida el JSON entrante. `NoteSerializer` expone el identificador de categoría y representaciones legibles de categoría y etiquetas.\n\n```json\n{\n  "title": "Mi nota",\n  "summary": "Una explicación breve",\n  "content": "# Hola",\n  "category": 1,\n  "difficulty": "beginner",\n  "status": "draft"\n}\n```\n\n## ViewSets y routers\n\n`NoteViewSet` concentra las operaciones del recurso y el router genera las rutas consistentes. Esto no mezcla la API con los templates: `webapi/` tiene sus serializers, vistas y URLs; `web/` tiene HTML, formularios y templates.\n\n## Búsqueda y filtros\n\nPuedes consultar `?search=modelos`, `?difficulty=beginner`, `?category=1` u ordenar con `?ordering=learning_order`. Los filtros deben estar declarados en el backend, no improvisados leyendo parámetros sin validar.\n\n## Permisos\n\nLa lectura de apuntes publicados es pública. Las operaciones de escritura requieren autenticación y privilegios de propietario. La interfaz y la API deben aplicar la misma regla aunque tengan clientes distintos.\n\n## Documentación y práctica\n\nAbre `/api/docs/` y prueba una consulta. Después usa `curl`: `curl http://127.0.0.1:8000/api/notes/?search=modelos`.\n\n1. Añade un campo de solo lectura al serializer.\n2. Escribe una prueba para un filtro.\n3. Comprueba la respuesta de un slug inexistente.\n4. Explica por qué un serializer no es un template.\n\n> Comprobación: describe el contrato de un endpoint sin mirar su implementación: URL, método, entrada, salida y permisos.""", "api", "intermediate", ["api", "rest"]),
]

class Command(BaseCommand):
    help = "Carga categorías, etiquetas y apuntes iniciales para estudiar Django."
    def handle(self, *args, **options):
        categories = {"fundamentals": ("Fundamentos", "Las piezas esenciales de Django."), "web": ("Web", "URLs, vistas, templates y formularios."), "api": ("APIs", "Diseño y consumo de APIs REST.")}
        for key, (name, description) in categories.items(): Category.objects.update_or_create(slug=key, defaults={"name": name, "description": description})
        for order, title, summary, content, category, difficulty, tag_names in NOTES:
            tags = [Tag.objects.get_or_create(slug=t, defaults={"name": t.replace("-", " ").title()})[0] for t in tag_names]
            note, _ = Note.objects.update_or_create(
                title=title,
                defaults={
                    "slug": slugify(title),
                    "summary": summary,
                    "content": content,
                    "category": Category.objects.get(slug=category),
                    "difficulty": difficulty,
                    "learning_order": order,
                    "status": Note.Status.PUBLISHED,
                },
            )
            note.tags.set(tags)
        self.stdout.write(self.style.SUCCESS(f"{len(NOTES)} apuntes iniciales cargados."))
